apiVersion: v2
name: tachyon
description: Tachyon - Faster-than-light tunneling for developers
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - tunnel
  - proxy
  - networking
  - https
  - ngrok

home: https://github.com/DrRuin/tachyon
sources:
  - https://github.com/DrRuin/tachyon

maintainers:
  - name: Tachyon Team
    url: https://github.com/DrRuin

icon: https://raw.githubusercontent.com/DrRuin/tachyon/main/docs/logo.svg

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: networking
